###
# This is the place to override the mod_php5_apache2 cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "mod_php5_apache2/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the mod_php5_apache2 packages:
#

normal[:mod_php5_apache2][:packages] = [ 'php56-devel',
                                         'php56-mcrypt',
                                         'php56-mbstring',
                                         'php56-gd',
                                         'php56-bcmath',
                                         'php56-tidy',
                                         'php56-pdo',
                                         'php56-mysqlnd',
                                         'php56-pecl-apcu',
					 'php56-pecl-memcached',
					 'php56-opcache' ]
